#pragma once

#include "common_types.h"

#include <array>
#include <sstream>

using namespace Common;

namespace TradingSystem{
    // We use struct bcs it is Plain Data Structure
    // structures like this are used via memory pool
    struct MarketOrder{
        OrderId orderId_ = OrderId_INVALID;
        Side side_ = Side::INVALID;
        Price price_ = Price_INVALID;
        Qty qty_ = Qty_INVALID;
        Priority priority_ = Priority_INVALID;

        MarketOrder* next_order_ = nullptr;
        MarketOrder* prev_order_ = nullptr;

        // ctor is generated by compiler
        // We do it for sake memory pool
        MarketOrder() = default;

        MarketOrder(OrderId orderId, Side side, Price price, Qty qty, Priority priority, MarketOrder* next, MarketOrder* prev)
            : orderId_(orderId), side_(side), price_(price), qty_(qty), priority_(priority), next_order_(next), prev_order_(prev){}

        // const after a method means the method does not modify the object state.
        auto toString() const -> std::string;
    };

    // TODO: Refacor to store sum_qty and order_count per Price level
    // it is good performance fix
    struct MarketOrderPriceLevel{
        Side side_ = Side::INVALID;
        Price price_ = Price_INVALID;

        MarketOrder* first_order_ = nullptr;

        MarketOrderPriceLevel* prev_level_ = nullptr;
        MarketOrderPriceLevel* next_level_ = nullptr;

        MarketOrderPriceLevel() = default;
        MarketOrderPriceLevel(Side side, Price price, MarketOrder* first_order, MarketOrderPriceLevel* prev_level, MarketOrderPriceLevel* next_level)
            : side_(side), price_(price), first_order_(first_order), prev_level_(prev_level), next_level_(next_level){}

        auto toString() const -> std::string;
    };

    // The Best Bid and Offer (BBO) represents the highest available buying price (bid) and the lowest available selling price (ask/offer) 
    // for an asset at any given moment
    struct BestBidOffer {
        Price bid_price_ = Price_INVALID;
        Qty bid_qty_ = Price_INVALID;

        Price ask_price_ = Price_INVALID;
        Qty ask_qty_ = Price_INVALID;

        auto toString() const -> std::string;
    };

    typedef std::array<MarketOrder*, ME_MAX_ORDER_IDS> MarketOrderHashMap;
    typedef std::array<MarketOrderPriceLevel*, ME_MAX_PRICE_LEVELS> MarketOrderPriceLevelsHashMap;
};