#pragma once

#include "market_order_book.h"
#include "common_types.h"

using namespace Common;

namespace TradingSystem{

    // We use struct bcs it is Plain Data Structure
    // structures like this are used via memory pool
    struct MarketOrder{
        OrderId orderId_ = OrderId_INVALID;
        Side side_ = Side::INVALID;
        Price price_ = Price_INVALID;
        Qty qty_ = Qty_INVALID;
        Priority priority_ = Priority_INVALID;

        MarketOrder* next_order_ = nullptr;
        MarketOrder* prev_order_ = nullptr;

        // ctor is generated by compiler
        // We do it for sake memory pool
        MarketOrder() = default;

        MarketOrder(OrderId orderId, Side side, Price price, Qty qty, Priority priority, MarketOrder* next, MarketOrder* prev)
            : orderId_(orderId), side_(side), price_(price), qty_(qty), priority_(priority), next_order_(next), prev_order_(prev){}

        // const after a method means the method does not modify the object state.
        auto toString() const -> std::string;
    };

    typedef std::array<MarketOrderBook*, ME_MAX_TICKERS> MarketOrderBookHashMap;
};